### ISSUE TITLE
Android Course Pre-requisite : TODO app

### ISSUE THREAD

**Issue by netra-m** [netra-m/ToDoApp#1]
Please review @codepathreview and @codepath

**Comment by nesquena** [comment]
Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program starts.

Nice job with the project, hope you found it as a helpful introduction to the platform and see you on Tuesday!

**Comment by nesquena** [comment]
You can now access the portal at [courses.codepath.com](http://courses.codepath.com) and the first assignment [here](http://courses.codepath.com/courses/intro_to_android/week/1#!assignment). Due Monday @ 10pm
